Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/routeros-long-term"
  config.vm.network "forwarded_port", guest: 8728, host: 8728, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8729, host: 8729, protocol: "tcp"
  config.vm.provision "routeros_file", name: "Upload router.crt", source: "router.crt", destination: "router.crt"
  config.vm.provision "routeros_file", name: "Upload router.key", source: "router.key", destination: "router.key"
  config.vm.provision "routeros_command", name: "Import router.crt", command: '/certificate import file-name=router.crt passphrase="" name=router'
  config.vm.provision "routeros_command", name: "Import router.key", command: '/certificate import file-name=router.key passphrase=""'
  config.vm.provision "routeros_command", name: "Enable api", command: "/ip service set api disabled=no"
  config.vm.provision "routeros_command", name: "Enable api-ssl", command: "/ip service set api-ssl disabled=no certificate=router"
end
